inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 160

Airbnb/ModuleMethodInWrongFile:
  Exclude:
    - app/models/spree/product_decorator.rb

AllCops:
  Exclude:
    - db/**/*
    - bin/*
    - config/**/*
    - lib/tasks/*
    - vendor/**/*
    - spec/*